services:
  - type: web
    name: rocketbot-playground
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: AUTH_USER
        sync: false
      - key: AUTH_PASSWORD
        sync: false
      - key: SESSION_SECRET
        generateValue: true
